language: java
dist: xenial
sudo: required
before_install:
- sudo apt update
- sudo apt install software-properties-common python-software-properties -y
- sudo apt-add-repository ppa:wpilib/toolchain -y && sudo add-apt-repository ppa:openjdk-r/ppa
  -y && sudo apt update
- sudo apt install default-jdk frc-toolchain -y
script: cd 2019Robot && chmod 777 gradlew && ./gradlew assemble
